# Generated by Django 3.1.5 on 2021-02-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='conteudo',
            field=models.TextField(max_length=500),
        ),
    ]
